---

- name: Install lsof since it is a prerequisite
  yum:
    name: lsof
    state: installed

- name: Check if Apache SOLR has been already installed
  stat:
    path: /opt/solr-{{ solr_version }}
  register: solr_installed

- name: Download Apache SOLR package
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
    dest: /usr/local/src/
  when: not solr_installed.stat.exists

- name: Unarchive Apache SOLR package
  unarchive:
    src: /usr/local/src/solr-{{ solr_version }}.tgz
    dest: /opt/
    remote_src: yes
  when: not solr_installed.stat.exists

- name: Set up init.d script
  template:
    src: solr.init.j2
    dest: /etc/init.d/solr
    mode: 0755

- name: Copy solr.in.sh to /etc/default/solr
  copy:
    src: /opt/solr-{{ solr_version }}/bin/solr.in.sh
    dest: /etc/default/solr
    mode: 0644
    remote_src: yes

- name: Enable the service
  service:
    name: solr
    enabled: yes
    state: started
